version: '3.8'
services:
    web:
        # Build image from source in localhost only
        # Use remote image instead in other cases
        build: .
        ports:
            - '8081:8081' # Should be quoted
